blackjack4494/youtube-dlc

- youtube_dl/extractor/viki.py
---
---
Explanation of your *pull request* in arbitrary form goes here. Please make sure the description explains the purpose and effect of your *pull request* and is worded well enough to be understood. Provide as much context and examples as possible.
Fixes the viki extractor. Login is working again as well as downloading up to 1080p
> Viki the second

- youtube_dl/extractor/extractors.py
- youtube_dl/extractor/hrfensehen.py
https://github.com/ytdl-org/youtube-dl/pull/26445
> [hrfernsehen] add extractor

- make_win.bat
installed pyinstaller required.
> [skip travis] simple bat for win binary

- youtube_dl/extractor/extractors.py
- youtube_dl/extractor/storyfire.py
https://github.com/ytdl-org/youtube-dl/pull/26349
> [StoryFire] Add new extractor

- youtube_dl/extractor/doodstream.py
- youtube_dl/extractor/extractors.py
https://github.com/ytdl-org/youtube-dl/pull/26345
> Doodstream

- youtube_dl/extractor/francetv.py
https://github.com/ytdl-org/youtube-dl/pull/26327
> [francetv] fix extractor

- youtube_dl/extractor/videa.py
https://github.com/ytdl-org/youtube-dl/pull/26301
> [videa] Adapt to updates

- youtube_dl/YoutubeDL.py
- youtube_dl/downloader/__init__.py
- youtube_dl/downloader/youtube_live_chat.py
- youtube_dl/extractor/youtube.py
https://github.com/ytdl-org/youtube-dl/pull/26240
> Youtube live chat

- youtube_dl/extractor/youtube.py
https://github.com/ytdl-org/youtube-dl/pull/26100
> [youtube] Fix age gate detection

- youtube_dl/utils.py
https://github.com/ytdl-org/youtube-dl/pull/26463
> [soundcloud] Resolve audio/x-wav

- setup.py
> [skip travis] fix broken setup.py

- youtube_dl/extractor/extractors.py
- youtube_dl/extractor/pokemon.py
https://github.com/ytdl-org/youtube-dl/pull/22626
alternative but repo got deleted
https://github.com/ytdl-org/youtube-dl/pull/23354
related issues
https://github.com/ytdl-org/youtube-dl/issues/22517
> [pokemon] add extractor for watch.pokemon.com

- youtube_dl/extractor/extractors.py
- youtube_dl/extractor/tvnow.py
@TinyToweringTree
https://github.com/ytdl-org/youtube-dl/pull/22364
related issues
https://github.com/ytdl-org/youtube-dl/issues/26516
https://github.com/ytdl-org/youtube-dl/issues/25817
https://github.com/ytdl-org/youtube-dl/issues/23940
https://github.com/ytdl-org/youtube-dl/issues/21201
https://github.com/ytdl-org/youtube-dl/issues/21455
interesting
https://github.com/ytdl-org/youtube-dl/issues/21900
> [tvnow] Add an extractor for films (closes #21455)

- youtube_dlc/extractor/soundcloud.py
include tests (weekly + charts)
weekly with login worked before. but now also public weekly will work. charts and similar patterned sets as well
> [soundcloud] sets pattern and tests

- youtube_dl/extractor/wdr.py
https://github.com/ytdl-org/youtube-dl/pull/22723
https://github.com/ytdl-org/youtube-dl/issues/22672
already tested. it works.
@mrtnmtth
> [wdr] fix subtitle extraction

- youtube_dl/extractor/ondemandkorea.py
https://github.com/ytdl-org/youtube-dl/pull/25877
> Ondemandkorea

- youtube_dl/extractor/ard.py
https://github.com/ytdl-org/youtube-dl/pull/25783
> [ard.py] add playlist support

- youtube_dl/extractor/extractors.py
- youtube_dl/extractor/magentamusik360.py
https://github.com/ytdl-org/youtube-dl/pull/24765
> [magentamusik360] Add new extractor

- youtube_dl/extractor/rutv.py
https://github.com/ytdl-org/youtube-dl/pull/26335
> [rutv] Fix JSON URL (closes #26333)

- youtube_dl/extractor/googledrive.py
https://github.com/ytdl-org/youtube-dl/pull/24689
> [gdrive] Fix/google drive cookie issue

- youtube_dl/extractor/rai.py
https://github.com/ytdl-org/youtube-dl/pull/23040
> [rai] Fix extraction for recent raiplay.it updates

- youtube_dl/extractor/extractors.py
- youtube_dl/extractor/myvideoge.py
https://github.com/ytdl-org/youtube-dl/pull/26283
> [MyVideoGe] add new extractor

- youtube_dl/extractor/rtlnl.py
https://github.com/ytdl-org/youtube-dl/pull/26549
> [rtl.nl] url pattern

- youtube_dl/extractor/bitchute.py
https://github.com/ytdl-org/youtube-dl/pull/26569
> [bitchute] Fix error for geoblocking

- youtube_dl/extractor/duboku.py
- youtube_dl/extractor/extractors.py
https://github.com/ytdl-org/youtube-dl/pull/26467
@lkho
> [duboku] new extractor

- youtube_dlc/extractor/ndr.py
---
---
Explanation of your *pull request* in arbitrary form goes here. Please make sure the description explains the purpose and effect of your *pull request* and is worded well enough to be understood. Provide as much context and examples as possible.
https://github.com/blackjack4494/youtube-dlc/issues/67
https://github.com/ytdl-org/youtube-dl/issues/26563
> [ndr] support Daserste ndr

- youtube_dlc/extractor/kakao.py
there are also ageLimit and GeoBlock attributes provided by api_json if needed
---
---
Explanation of your *pull request* in arbitrary form goes here. Please make sure the description explains the purpose and effect of your *pull request* and is worded well enough to be understood. Provide as much context and examples as possible.
https://github.com/blackjack4494/youtube-dlc/pull/90
https://github.com/ytdl-org/youtube-dl/pull/26577
https://github.com/ytdl-org/youtube-dl/pull/14482
https://github.com/ytdl-org/youtube-dl/pull/14007 …
> [kakao] new apis

- youtube_dlc/extractor/gdcvault.py
at least when not logged in?
---
---
Explanation of your *pull request* in arbitrary form goes here. Please make sure the description explains the purpose and effect of your *pull request* and is worded well enough to be understood. Provide as much context and examples as possible.
> [gdcvault] fix extractor

- .github/ISSUE_TEMPLATE/1_broken_site.md
- .github/ISSUE_TEMPLATE/2_site_support_request.md
- .github/ISSUE_TEMPLATE/3_site_feature_request.md
- .github/ISSUE_TEMPLATE/4_bug_report.md
- .github/ISSUE_TEMPLATE/5_feature_request.md
- ChangeLog
- docs/supportedsites.md
- youtube_dl/extractor/extractors.py
- youtube_dl/extractor/googledrive.py
- youtube_dl/extractor/redbulltv.py
- youtube_dl/extractor/rtlnl.py
- youtube_dl/extractor/soundcloud.py
- youtube_dl/extractor/srgssr.py
- youtube_dl/extractor/svt.py
- youtube_dl/extractor/youtube.py
- youtube_dl/postprocessor/embedthumbnail.py
- youtube_dl/version.py
Have to manually check changed and may have to adapt them a bit.
> [youtube-dl] merge updated master

- youtube_dl/extractor/mitele.py
DjMoren
https://github.com/ytdl-org/youtube-dl/pull/25827
[reddit](https://www.reddit.com/r/DataHoarder/comments/ir8ic6/youtubedlc_an_active_fork_of_youtubedl/g53d6jx/?utm_source=reddit&utm_medium=web2x&context=3)
> Add extraction logic to mitele for videos not based in ooyala

- youtube_dl/extractor/elonet.py
- youtube_dl/extractor/extractors.py
@tpikonen
https://github.com/ytdl-org/youtube-dl/pull/26547
@mrderp @vkk800
https://github.com/ytdl-org/youtube-dl/issues/24774
> [elonet] Add extractor (closes #24774)

- README.md
- devscripts/fish-completion.py
- devscripts/zsh-completion.in
- youtube_dl/__init__.py
- youtube_dl/options.py
- youtube_dl/postprocessor/__init__.py
- youtube_dl/postprocessor/ffmpeg.py
@Zocker1999NET
https://github.com/ytdl-org/youtube-dl/pull/25296
@nielsmh @altimumdelta @gw711 
https://github.com/ytdl-org/youtube-dl/issues/6996
@user0150
> [Core] Added --remux-video option

- youtube_dlc/YoutubeDL.py
- I am the original author of this code and I am willing to release it under [Unlicense](http://unlicense.org/)
Fixes #122
> Keep download archive in memory for better performance

- youtube_dl/extractor/extractors.py
- youtube_dl/extractor/naver.py
@SeonjaeHyeon
https://github.com/ytdl-org/youtube-dl/pull/26610
> [naver] Add support for live videos

- .github/workflows/build.yml
- scripts/update-version-workflow.py
- youtube_dlc/version.py
> Release v3 2020.09.23

- youtube_dlc/extractor/go.py
---
Code was pulled from the PR on the  ytdl-org/youtube-dl repo (https://github.com/ytdl-org/youtube-dl/pull/25216)
---
Just copied regex from youtube-dl.
> Added regex for ABC.com site.

- .github/workflows/build.yml
- pyinst.py
- pyinst32.py
- scripts/update-version.py
- youtube_dlc/YoutubeDL.py
- youtube_dlc/__init__.py
- youtube_dlc/extractor/bandcamp.py
- youtube_dlc/extractor/hotstar.py
- youtube_dlc/extractor/tiktok.py
- youtube_dlc/options.py
- youtube_dlc/version.py
> Release 2020.09.30

- youtube_dl/extractor/youtube.py
@RedpointsBots
https://github.com/ytdl-org/youtube-dl/pull/26679
related issues
https://github.com/blackjack4494/youtube-dlc/issues/164
> [youtube] Update extraction of like/dislike count

- youtube_dl/extractor/youtube.py
@RedpointsBots
https://github.com/ytdl-org/youtube-dl/pull/26678
maybe there should be something mentioned in the docs about this.
> [youtube] Added 'subscriber_count' to extraction

- youtube_dl/extractor/bandcamp.py
@gilou
https://github.com/ytdl-org/youtube-dl/pull/26684
https://github.com/blackjack4494/youtube-dlc/issues/148 @dym-sh
> [Bandcamp] update - fix regexp for JSON matching

- youtube_dlc/extractor/bet.py
- youtube_dlc/extractor/cmt.py
- youtube_dlc/extractor/comedycentral.py
- youtube_dlc/extractor/mtv.py
- youtube_dlc/extractor/nick.py
- youtube_dlc/extractor/spike.py
- youtube_dlc/extractor/vh1.py
- youtube_dlc/utils.py
@StevenDTX
https://github.com/blackjack4494/youtube-dlc/issues/175
kinda related
https://github.com/blackjack4494/youtube-dlc/issues/44
> [Mtv] updated extractor logic & more

- youtube_dlc/extractor/mtv.py
- youtube_dlc/extractor/southpark.py
closing https://github.com/blackjack4494/youtube-dlc/issues/187
> [SouthparkDE/MTV] another mgid extraction (mtv_base) feed url updated

- youtube_dlc/extractor/mtv.py
- youtube_dlc/extractor/nick.py
> [MTV/Nick] universal mgid extractor + fix nick.de feed

- docs/supportedsites.md
- youtube_dlc/extractor/extractors.py
- youtube_dlc/extractor/twitter.py
> Twitter shortener
